version: "3"

services:

  node-app:
    build:
      dockerfile: Dockerfile.node-app
    # restart: always
    network_mode: host
    # format: <MATTERBRIDGE_API_ADDRESS> <MATTERBRIDGE_GATEWAY> <SIMPLEX_LISTEN_ADDRESS> <SIMPLEX_CHAT_ID> <CHAT_TYPE (contact/group)>
    command: 127.0.0.1:4242 gateway1 127.0.0.1:5225 1 group

  simplex:
    build:
      dockerfile: Dockerfile.simplex
    # restart: always
    volumes:
      - ./data/simplex:/app/.simplex/
    # must be host mode, because simplex websocket always liten only on
    # 127.0.0.1
    network_mode: host

  matterbridge:
    build:
      dockerfile: Dockerfile.matterbridge
    # restart: always
    volumes:
      - ./matterbridge.toml:/app/matterbridge.toml
    network_mode: host
