FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
  wget \
  && rm -rf /var/cache/apk/* && apt-get autoremove -y && apt-get clean

WORKDIR /app
RUN wget \
    "https://github.com/simplex-chat/simplex-chat/releases/download/v6.4.0/simplex-chat-ubuntu-24_04-x86-64" \
    -O ./simplex-chat
RUN chmod +x ./simplex-chat

# set non-root user
RUN useradd -rm -d /app -s /bin/bash -g root -G sudo -u 1001 app
USER app

ENTRYPOINT ["/app/simplex-chat", "-p", "5225"]
