version: "3"

services:

  simplex:
    build:
      dockerfile: Dockerfile.simplex
    # restart: always
    volumes:
      - ./data/simplex:/app/.simplex/

  matterbridge:
    build:
      dockerfile: Dockerfile.matterbridge
    # restart: always
    volumes:
      - ./config/matterbridge.toml:/app/matterbridge.toml
