[sshchat.my]
Server="localhost:48320"
Nick="matterbridge"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[api.my]
BindAddress="127.0.0.1:4242"
Buffer=1000
RemoteNickFormat="{NICK}"


[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="sshchat.my"
channel="sshchat"

[[gateway.inout]]
account="api.my"
channel="api"
